apiVersion: v1
kind: Pod
metadata:
  name: online-inference-res
  labels:
    app: online-inference-res
spec:
  containers:
    - image: mlops_hw2:v8
      name: model-res
      ports:
        - containerPort: 8000
      resources:
        requests:
            memory: "512Mi"
            cpu: "250m"
        limits:
            memory: "1Gi"
            cpu: "500m"